In [174]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [175]:
df=pd.read_csv("food_profit_item_level.csv")
df

,day_type,weather,location_type,time_of_day,item_type,footfall,item_price,cost_price,demand,profit
0,Weekday,Sunny,Residential,Evening,Maggie,121,68,39.38,33.94,971.52
1,Weekday,Sunny,Residential,Evening,Sandwich,121,92,38.40,52.25,2800.47
2,Weekday,Sunny,Residential,Evening,Tea,121,13,5.76,35.73,258.77
3,Weekday,Sunny,Residential,Evening,Cold Drink,121,50,34.55,63.48,980.80
4,Weekend,Rainy,College,Morning,Maggie,253,65,36.23,87.13,2506.40
...,...,...,...,...,...,...,...,...,...,...
1595,Weekday,Cloudy,College,Evening,Cold Drink,264,52,34.99,83.21,1414.94
1596,Weekend,Sunny,Residential,Morning,Maggie,192,66,35.45,46.57,1422.77
1597,Weekend,Sunny,Residential,Morning,Sandwich,192,81,43.95,62.80,2326.47
1598,Weekend,Sunny,Residential,Morning,Tea,192,26,11.05,89.58,1339.27
1599,Weekend,Sunny,Residential,Morning,Cold Drink,192,52,27.46,38.40,942.46

# 2. EDA

In [176]:
df.isna().sum().sum()

0

In [177]:
df.describe()

          footfall   item_price   cost_price       demand       profit
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000
mean    178.085000    52.433750    28.962519    50.965781  1146.824175
std      71.085097    23.259084    13.561690    31.119642   875.782977
min      50.000000    10.000000     4.080000     5.250000    39.680000
25%     122.000000    35.000000    19.152500    27.410000   517.877500
50%     176.500000    50.000000    27.720000    43.025000   904.980000
75%     241.000000    69.250000    37.482500    67.632500  1528.025000
max     299.000000    99.000000    68.060000   203.380000  5843.470000

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   day_type       1600 non-null   object
 1   weather        1600 non-null   object
 2   location_type  1600 non-null   object
 3   time_of_day    1600 non-null   object
 4   item_type      1600 non-null   object
 5   footfall       1600 non-null   int64
 6   item_price     1600 non-null   int64
 7   cost_price     1600 non-null   float64
 8   demand         1600 non-null   float64
 9   profit         1600 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 125.1+ KB

## Handling Categorical Values

In [179]:
df.columns

Index(['day_type', 'weather', 'location_type', 'time_of_day', 'item_type',
       'footfall', 'item_price', 'cost_price', 'demand', 'profit'],
      dtype='object')

In [180]:
df["day_type"].value_counts()

Weekday    836
Weekend    764
Name: day_type, dtype: int64

In [181]:
d1={'Weekday':0,'Weekend':1}
df["day_type"]=df["day_type"].map(d1)

In [182]:
df["day_type"].value_counts()

0    836
1    764
Name: day_type, dtype: int64

In [183]:
df['weather'].value_counts()

Sunny     576
Cloudy    540
Rainy     484
Name: weather, dtype: int64

In [184]:
w={'Sunny':0,'Cloudy':1,'Rainy':2}
df['weather']=df['weather'].map(w)

In [185]:
df['weather'].value_counts()

0    576
1    540
2    484
Name: weather, dtype: int64

In [186]:
df['location_type'].value_counts()

College        552
Residential    544
Office         504
Name: location_type, dtype: int64

In [187]:
loc={'College':0,'Residential':1,'Office':2}
df['location_type']=df['location_type'].map(loc)

In [188]:
df['location_type'].value_counts()

0    552
1    544
2    504
Name: location_type, dtype: int64

In [189]:
df['time_of_day'].value_counts()

Evening      568
Morning      552
Afternoon    480
Name: time_of_day, dtype: int64

In [190]:
t={'Evening':0,'Morning':1,'Afternoon':2}
df['time_of_day']=df['time_of_day'].map(t)

In [191]:
df['time_of_day'].value_counts()

0    568
1    552
2    480
Name: time_of_day, dtype: int64

In [192]:
df['item_type'].value_counts()

Maggie        400
Sandwich      400
Tea           400
Cold Drink    400
Name: item_type, dtype: int64

In [193]:
menu={'Maggie':0,'Sandwich':1,'Tea':2,'Cold Drink':3}
df['item_type']=df['item_type'].map(menu)

In [194]:
df['item_type'].value_counts()

0    400
1    400
2    400
3    400
Name: item_type, dtype: int64

# 3.Model Building

In [195]:
df.columns

Index(['day_type', 'weather', 'location_type', 'time_of_day', 'item_type',
       'footfall', 'item_price', 'cost_price', 'demand', 'profit'],
      dtype='object')

In [196]:
df['margin'] = df['item_price'] - df['cost_price']

In [197]:
df['price_per_customer'] = df['item_price'] / df['footfall']

In [198]:
X=df[['day_type', 'weather', 'location_type', 'time_of_day', 'item_type','footfall', 'item_price', 'cost_price']]
y=df['demand']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [199]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [200]:
y_pred = model.predict(x_test)
y_pred

array([67.43323517, 59.10085597, 67.1262114 , 25.56375951, 55.8359372 ,
       42.50483873, 22.49805319,  7.46682083, 56.20288236, 58.11774126,
       48.57461757, 63.09145543, 84.01169581, 54.16595565, 26.20520216,
       89.99278334, 49.38190374, 61.43942218, 68.26443396, 21.79773532,
       33.07596473, 83.31435055, 58.24817117, 23.73724643, 35.82355668,
       44.80667434, 26.85898525, 51.14734038, 45.81499696, 20.33836166,
       53.66381727, 41.29500272, 24.60593106, 80.0019768 , 88.30017756,
       83.59392699, 34.93843362, 59.39486373, 63.61289797, 68.24974588,
       70.94262705, 55.93968524, 89.99256477, 23.29842948, 98.63101499,
       67.8468104 , 62.02293098, 25.8793533 , 56.74007624, 56.47570599,
       35.1982812 , 74.10881522, 72.49867585, 27.0227441 , 23.05898216,
       55.86339694, 33.3773406 , 30.45933335, 15.74079805, 28.77546968,
       44.4162426 , 87.52455603, 24.13451522, 67.86992256, 83.20246491,
       68.24529553, 79.56044282, 75.50406438, 51.98389265, 34.39333504,
       26.53830356, 80.32309792, 74.57538265, 52.07929452, 67.33027811,
       38.41170138, 38.16152773, 35.99018809, 50.64562204, 22.47336822,
       57.99529632, 68.74473814, 56.45368642,  9.99706305, 51.55195588,
       26.71458101, 60.76880875, 72.26556706, 62.51422474, 32.5301348 ,
       58.16505207, 67.70138905, 58.43817467, 46.96031883, 48.15153085,
       44.64404817, 33.00511395, 55.22114241, 53.17165261, 61.40573887,
       45.0865533 , 78.19106405, 40.72575477, 61.06298095, 22.71265569,
       76.7162846 , 77.59596461,  2.98278407, 69.15506705, 39.60955931,
       77.36442313, 68.25431568, 52.68696022, 30.35891271, 56.94111081,
       42.92442336, 52.57430979, 67.69312941, 80.96912592, 55.0318689 ,
       50.66533565, 86.98325075, 49.31548602, 66.19849833, 24.21698119,
       12.83076257, 51.37351294, 63.22003561, 43.27607415, 43.0483532 ,
       49.14127729, 41.72751792, 28.12521491, 74.29482142, 15.12756178,
       91.82631696, 38.68084507, 77.50263944, 81.97370985, 52.46497599,
       81.37677933, 57.98936034, 38.652853  , 58.63782617, 36.5492103 ,
       26.15281967, 46.20886454, 65.06024629, 53.63779421, 53.63968945,
       52.92649495, 77.72979942, 14.83480806, 44.23224835, 79.19922414,
       51.48091425, 41.44095274, 44.61981939, 55.01486672, 74.6292257 ,
       10.60341022, 34.70790115, 43.84624984, 80.40510037, 54.02463641,
       82.0032014 , 37.71419557, 54.79908317, 58.08330642, 31.04647584,
       57.18864076, 45.06639404, 27.54688051, 72.56372319, 25.13028062,
       65.60458465, 55.10682884, 41.64477715, 16.45575332, 49.39610073,
       17.33303448, 50.73487523, 63.13809969, 70.85905621, 76.95684424,
       16.04477931, 49.20659315, 72.94479081, 73.35496271, 88.25489649,
       76.9030443 , 34.42510362, 74.77810309, 33.97829788, 12.82150415,
       82.13889611, 75.11495569, 32.62954935, 66.5996772 , 65.75349183,
       82.83461151, 79.39162928, 46.34888527, 26.84000124, 64.75373379,
       39.66940701, 31.0844425 , 19.36073217, 31.85812982, 22.1399198 ,
       40.74916844, 89.56238025, 53.56677316, 63.6467986 , 74.33991333,
       26.79741545, 83.68115484, 30.60154946, 56.50646303, 80.76316039,
       82.40370526, 84.96544402, 74.45584335, 42.52216156, 47.93750392,
       49.8313718 , 20.14607929, 46.27571649, 73.1244504 , 57.56476168,
       48.36084367, 62.44212423, 33.81181223, 90.16940571, 38.51494277,
       19.21472319, 44.27808613, 48.82984465, 19.2499988 , 14.9265738 ,
       59.3603913 , 19.0942417 , 39.50617041, 63.2772542 , 46.7970827 ,
       18.25223307, 45.05139713, 43.86725327, 23.40540893, 31.79695298,
       64.57632818, 81.37349824, 68.69606456, 13.57790064, 25.05363626,
       55.98453449, 17.38922703, 77.68195505, 58.0020949 , 24.66405402,
       53.02451533, 53.46178316, 47.06846152, 78.67872221, 45.21522197,
       85.67191958, 71.02529483, 90.07602069, 62.36808518, 85.81131663,
       38.56307146, 59.1117697 , 11.58333742, 43.12256258, 76.35580354,
       44.02380406, 53.09165232, 66.85751205, 44.28254298, 51.512609  ,
       33.90563972, 14.90357417, 32.14550221, 56.43921329, 18.28353534,
       32.24639754, 45.89593624, 37.72539532, 45.08780743, 58.06067512,
       55.73860317, 95.77309478, 80.83432244, 69.50746827, 41.06936644,
       81.18803261, 42.06561032, 77.39408528, 80.40490112, 71.71697336,
       58.39855068, 71.13352382, 57.73271092, 55.67291235, 31.2371872 ,
       81.35079178, 20.74884117, 81.52803099, 33.09633092, 53.42721318,
       45.06732101, 27.51583074, 55.77413732, 57.18255271, 82.54955834,
       33.78332156, 27.01128   , 75.41328527, 48.29150045, 47.65687437])

In [201]:
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.40429700647131883

In [202]:
day_type = input("Day Type (Weekday/Weekend): ")
weather = input("Weather (Sunny/Cloudy/Rainy): ")
location_type = input("Location (College/Residential/Office): ")
time_of_day = input("Time (Morning/Afternoon/Evening): ")
item_type = input("Item (Maggie/Sandwich/Tea/Cold Drink): ")

footfall = int(input("Footfall: "))
cost_price = float(input("Cost Price: "))


day = d1[day_type]
weather = w[weather]
location = loc[location_type]
daytime = t[time_of_day]
item = menu[item_type]

Day Type (Weekday/Weekend): Weekday
Weather (Sunny/Cloudy/Rainy): Sunny
Location (College/Residential/Office): Office
Time (Morning/Afternoon/Evening): Afternoon
Item (Maggie/Sandwich/Tea/Cold Drink): Cold Drink
Footfall: 23
Cost Price: 10

In [206]:
results = [] 
for price in range(20, 120, 10): # selling price # 20, 30, 40 ... 110
    test = [[day, weather, location, daytime, item,footfall, price, cost_price]]
    predicted_demand = int(model.predict(test)[0])
    profit = (price - cost_price) * predicted_demand
    results.append((price, predicted_demand, profit))
best = max(results, key=lambda x: x[2])  
print(best)

(30, 3, 60.0)

C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Tanuja\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [207]:
print("\nBest Price Strategy:")
print("Price:", best[0])
print("Expected Demand:", int(best[1]))
print("Expected Profit:", int(best[2]),"Rs")

Best Price Strategy:
Price: 30
Expected Demand: 3
Expected Profit: 60 Rs

In [208]:
print("\nAll Price Options:")
for r in results:
    print("Price:", r[0], "Demand:", r[1], "Profit:", r[2])

All Price Options:
Price: 20 Demand: 5 Profit: 50.0
Price: 30 Demand: 3 Profit: 60.0
Price: 40 Demand: 1 Profit: 30.0
Price: 50 Demand: -1 Profit: -40.0
Price: 60 Demand: -3 Profit: -150.0
Price: 70 Demand: -5 Profit: -300.0
Price: 80 Demand: -8 Profit: -560.0
Price: 90 Demand: -10 Profit: -800.0
Price: 100 Demand: -12 Profit: -1080.0
Price: 110 Demand: -14 Profit: -1400.0

In [209]:
import pickle

pickle.dump(model,open('price_recco_model.pkl','wb'))